name: green_bin
description: "A smart waste guidance app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  material_symbols_icons: ^4.2873.0
  cupertino_icons: ^1.0.8
  intl: ^0.20.2

  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  flutter_riverpod: ^2.6.1
  flutter_markdown: ^0.7.7+1

  geolocator: ^12.0.0
  flutter_google_maps_webservices: ^1.1.1
  url_launcher: ^6.3.0
  latlong2: ^0.9.1
  cached_network_image: ^3.4.1

  tflite_flutter: ^0.11.0     
  image_picker: ^0.8.5+3      
  image: ^4.0.17              

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/images/green_bin_icon.png"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"
  min_sdk_android: 21

flutter:

  uses-material-design: true

  assets:
     - assets/images/
     - assets/privacy_policy.md
     - assets/terms_and_conditions.md
     - assets/waste_classification_model.tflite
     - assets/labels.txt

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans/OpenSans-Medium.ttf
        - asset: assets/fonts/OpenSans/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans/OpenSans-SemiBold.ttf
          weight: 600
    - family: Poppins
      fonts:
         - asset: assets/fonts/Poppins/Poppins-Bold.ttf
           weight: 700
         - asset: assets/fonts/Poppins/Poppins-Light.ttf
           weight: 300
         - asset: assets/fonts/Poppins/Poppins-Medium.ttf
         - asset: assets/fonts/Poppins/Poppins-Regular.ttf
         - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
           weight: 600
