// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbbCz624zejTNAHTnlea-_eUFOxw2Ei0Q',
    appId: '1:122518635683:web:04931b7a72fe02f1182b16',
    messagingSenderId: '122518635683',
    projectId: 'greenbin-12bcs',
    authDomain: 'greenbin-12bcs.firebaseapp.com',
    storageBucket: 'greenbin-12bcs.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApVcOdrdvEbnFwm5u6imE0e8yPrS5CgbU',
    appId: '1:122518635683:android:09f5c8674c28a5ea182b16',
    messagingSenderId: '122518635683',
    projectId: 'greenbin-12bcs',
    storageBucket: 'greenbin-12bcs.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbxcxcXQWCC5KLY3nPzT_e-ypH6HjZXiI',
    appId: '1:122518635683:ios:f87306c7cbaf9855182b16',
    messagingSenderId: '122518635683',
    projectId: 'greenbin-12bcs',
    storageBucket: 'greenbin-12bcs.firebasestorage.app',
    iosBundleId: 'com.calvin.greenBin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbbCz624zejTNAHTnlea-_eUFOxw2Ei0Q',
    appId: '1:122518635683:web:dff5d2fc40514bbd182b16',
    messagingSenderId: '122518635683',
    projectId: 'greenbin-12bcs',
    authDomain: 'greenbin-12bcs.firebaseapp.com',
    storageBucket: 'greenbin-12bcs.firebasestorage.app',
  );
}
